### ISSUE TITLE
learn to english :((((((

### ISSUE THREAD

**Issue by visiblyisabelle** [infinityverse/Plug.djscript#1]

**Comment by xSapling** [comment]
xddddddddd

no

**Comment by visiblyisabelle** [comment]
this issue actually makes me want to die

**Comment by xSapling** [comment]
> this issue actually makes me want to die

REPORT ACCEPTED

Thanks for the report, the player in question has been dealt with. Thanks for keeping Mineplex clean!

**Comment by visiblyisabelle** [comment]
:thumb:
